[package]
name = "aws-benchmark"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "./compiletime-benchmark-remove",
    "./compiletime-benchmark-common",
    "./compiletime-benchmark-setup",
]
exclude = ["./serde-aws-sdk"]

[build]
rustflags = ["--cfg", "aws_sdk_unstable"]